name: Test, Build, and Push Image to Docker

on:
  push:
    branches:
      - 'master'
      - 'development'
    tags:
      - 'v*'

env:
  DOCKER_REPO_NAME: yumegel2/mywebclass

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16 
      - name: Install dependencies
        run: |
          npm install
          npm run build
          npx playwright install-deps
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest and playwright
        id: automated-tests
        run: |
          pytest -c pytest.ini
          npx playwright test --config=playwright.config.js
      - if: steps.automated-tests.outcome == 'success'
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_REPO_NAME }} 
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: 'linux/arm64/v8, linux/amd64'
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
